apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-hpa
  labels:
    app: example-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-hpa
  template:
    metadata:
      labels:
        app: example-hpa
    spec:
      containers:
      - name: example-hpa
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m