version: 2

jobs:

  test-terraform:
    docker:
      - image: snormore/doks-examples
    steps:
      - checkout
      - run: cd terraform && script/test

  test-network-policy:
    docker:
      - image: snormore/doks-examples
    steps:
      - checkout
      - run: cd network-policy && script/test

  test-monitoring:
    docker:
      - image: snormore/doks-examples
    steps:
      - checkout
      - run: cd monitoring && script/test

  test-istio:
    docker:
      - image: snormore/doks-examples
    steps:
      - checkout
      - run: cd istio && script/test

workflows:
  version: 2
  build:
    jobs:
      - test-terraform
      - test-network-policy
      - test-monitoring
      - test-istio