apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-local-pv
  labels:
    app: example-local-pv
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi