apiVersion: v1
kind: Pod
metadata:
  name: example-xfs
  labels:
    app: example-xfs
spec:
  containers:
  - name: example-xfs
    image: ubuntu
    command:
    - sleep
    - infinity
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: example-xfs