apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-xfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-xfs